#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Feb 12, 2021 08:57:35 PM JST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import group9_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    group9_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    group9_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("640x480+872+106")
        top.minsize(120, 1)
        top.maxsize(3844, 1061)
        top.resizable(1,  1)
        top.title("PSB Group 9")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Battler = tk.Canvas(top)
        self.Battler.place(relx=0.281, rely=0.0, relheight=1.0, relwidth=0.719)
        self.Battler.configure(background="#d9d9d9")
        self.Battler.configure(borderwidth="2")
        self.Battler.configure(highlightbackground="#d9d9d9")
        self.Battler.configure(highlightcolor="black")
        self.Battler.configure(insertbackground="black")
        self.Battler.configure(relief="ridge")
        self.Battler.configure(selectbackground="blue")
        self.Battler.configure(selectforeground="white")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.013, rely=0.013, height=21, width=34)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Coin''')

        self.TSeparator1 = ttk.Separator(top)
        self.TSeparator1.place(relx=0.0, rely=0.063,  relwidth=0.281)

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.016, rely=0.083, height=24, width=24)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''C''')

        self.lblCoin = tk.Label(top)
        self.lblCoin.place(relx=0.066, rely=0.083, height=21, width=124)
        self.lblCoin.configure(background="#d9d9d9")
        self.lblCoin.configure(disabledforeground="#a3a3a3")
        self.lblCoin.configure(foreground="#000000")
        self.lblCoin.configure(text='''314,159''')

        self.TSeparator2 = ttk.Separator(top)
        self.TSeparator2.place(relx=0.0, rely=0.152,  relwidth=0.283)

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.013, rely=0.167, height=21, width=164)
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Game Log''')

        self.txtLogBox = tk.Text(top)
        self.txtLogBox.place(relx=0.0, rely=0.221, relheight=0.623
                , relwidth=0.284)
        self.txtLogBox.configure(background="white")
        self.txtLogBox.configure(font="TkTextFont")
        self.txtLogBox.configure(foreground="black")
        self.txtLogBox.configure(highlightbackground="#d9d9d9")
        self.txtLogBox.configure(highlightcolor="black")
        self.txtLogBox.configure(insertbackground="black")
        self.txtLogBox.configure(selectbackground="blue")
        self.txtLogBox.configure(selectforeground="white")
        self.txtLogBox.configure(wrap="word")

        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.016, rely=0.919, height=27, width=64)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Option''')

        self.Button3 = tk.Button(top)
        self.Button3.place(relx=0.163, rely=0.919, height=27, width=68)
        self.Button3.configure(activebackground="#ececec")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#d9d9d9")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''Restart''')

if __name__ == '__main__':
    vp_start_gui()





